# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
  def toggle_div(div)
    update_page do |page|
      page[div].toggle
      page[div].visual_effect :highlight
    end
  end

  def language_options
    ['Anglo-Norman',
    'Arabic',
    'Azestan',
    'Chinese',
    'Cornish',
    'Czech',
    'Dutch',
    'English - Anglo-Saxon / Old English',
    'English - Middle English',
    'English - Scots',
    'Ethiopian',
    'French - Breton',
    'French - Gascon',
    'French - Old French',
    'French - Other',
    'French - Provencal',
    'German',
    'German - Middle High German',
    'Greek',
    'Hebrew',
    'Italian',
    'Latin',
    'Manx',
    'Old Norse',
    'Old/Middle Irish',
    'Other',
    'Pahlavi',
    'Pazand',
    'Persian',
    'Portuguese',
    'Russian',
    'Scottish Gaelic',
    'Spanish',
    'Spanish - Catalan',
    'Spanish - Medieval', 
    'Turkish',
    'Welsh' ]
  end

  def country_options
    ['Africa',
    'Algeria',
    'Armenia',
    'Asia',
    'Austria',
    'Balkans',
    'Belgium',
    'Bohemia',
    'British Isles',
    'Bulgaria',
    'Byzantium',
    'China',
    'Crete',
    'Czech Republic',
    'Denmark',
    'Egypt',
    'England',
    'Europe',
    'Finland',
    'Flanders',
    'France',
    'Germany',
    'Greece',
    'Holy Roman Empire',
    'Hungary',
    'Iberian Peninsula',
    'Iceland',
    'India',
    'Ireland',
    'Italy',
    'Middle East',
    'Netherlands',
    'New World',
    'Norway',
    'Persia',
    'Poland',
    'Portugal',
    'Prussia',
    'Russia',
    'Scandinavia',
    'Scotland',
    'Spain',
    'Sweden',
    'Switzerland',
    'Tunisia',
    'Turkey',
    'Ukraine',
    'Wales',
    'Yugoslavia' ]
  end

  def type_options
    ['Account Roll',
    'Account Roll - Bailiff/Reeve',
    'Account Roll - Building',
    'Account Roll - Estate',
    'Account Roll - Household',
    'Account Roll - Obedientiary',
    'Account Roll - Port Customs',
    'Biography',
    'Cartulary',
    'Charters, Deeds',
    'Chronicle, Annals',
    'Commentary / Gloss / Exegesis',
    'Contract',
    'Coroner\'s Roll',
    'Councils - Church',
    'Councils - Secular',
    'Court Roll',
    'Court Roll - Ecclesiastical',
    'Court Roll - Eyre',
    'Court Roll - Gaol Delivery',
    'Court Roll - Sessions of the Peace',
    'Custumal',
    'Dialog',
    'Disputation - Philosophical/Theological',
    'Extents and Surveys',
    'Formulary',
    'Genealogy',
    'Glossary / Dictionary',
    'Guild Records',
    'Hagiography',
    'Inquisition - Heresy',
    'Inscription',
    'Inventory',
    'Law - Canon Law',
    'Law - Legislation',
    'Law - Local Ordinances',
    'Law - Treatise/Commentary',
    'Letter',
    'Literature - Drama',
    'Literature - Prose',
    'Literature - Verse',
    'Liturgy',
    'Memoir',
    'Memoir - Family',
    'Miscellany',
    'Monastic Rule',
    'Muster',
    'Oration',
    'Other',
    'Papal Bull',
    'Petition',
    'Philosophic Work',
    'Prophecy', 
    'Proverbs',
    'Register - Bishop',
    'Register - Notarial',
    'Scripture',
    'Sermons',
    'Taxes',
    'Taxes - Clerical Subsidy',
    'Taxes - Lay Subsidy',
    'Taxes - Poll Tax',
    'Theology',
    'Theology - Devotional',
    'Theology - Doctrine',
    'Theology - Mystical Work',
    'Theology - Practical/Instructional',
    'Theology/Philosophy - Summa',
    'Translation',
    'Treatise - Instruction/Advice',
    'Treatise - Other',
    'Treatise - Political',
    'Treatise - Scientific/Medical',
    'Visitations',
    'Will' ]
  end

  def subject_options
    ['Agriculture',
    'Apocalypticism',
    'Architecture and Buildings',
    'Art',
    'Asiatic Nomads: Huns, Mongols, etc.',
    'Byzantium',
    'Carolingians',
    'Church Fathers',
    'Classics / Humanism',
    'Clergy - Anticlericalism',
    'Clergy - Monks, Nuns, Friars',
    'Clergy - Priests, Bishops, Canons',
    'Conversion',
    'Crusades',
    'Diplomacy',
    'Early Germanic Peoples: Goths, Franks, etc.',
    'Economy - Crafts and Industry',
    'Economy - Guilds and Labor',
    'Economy - Trade',
    'Education / Universities',
    'Family / Children',
    'Government',
    'Grammar / Rhetoric',
    'Heresy',
    'Historiography',
    'Jews / Judaism',
    'Law - Canon',
    'Law - Crime',
    'Law - Secular',
    'Literature - Arthurian',
    'Literature - Comedy / Satire',
    'Literature - Devotional',
    'Literature - Drama',
    'Literature - Epics, Romance',
    'Literature - Folklore, Legends',
    'Literature - Other',
    'Magic / Witchcraft',
    'Maritime',
    'Material Culture: Food, Clothing, Household',
    'Medicine',
    'Military Orders', 
    'Monasticism',
    'Music',
    'Muslims / Islam',
    'Nobility / Gentry',
    'Papacy',
    'Peasants',
    'Philosophy / Theology',
    'Philisophy - Aristotelian',
    'Philosophy - Ethics / Moral Theology',
    'Philosophy - Logic',
    'Philosophy - Metaphysics',
    'Philosophy - Platonic / Neo-Platonic',
    'Philosophy - Political',
    'Piety',
    'Piety - Confession, Penance',
    'Piety - Lay',
    'Piety - Mysticism',
    'Plague and Disease',
    'Political Thought',
    'Poverty / Charity',
    'Recreation',
    'Reform',
    'Religion - Institutional Church',
    'Revolt',
    'Royalty / Monarchs',
    'Saints',
    'Saints - Cults / Relics',
    'Science / Technology',
    'Science - Astronomy',
    'Science - Mathematics',
    'Theology - Christology',
    'Theology - Ecclesiology',
    'Theology - Eschatology',
    'Theology - Heretical',
    'Theology - History',
    'Theology - Mariology',
    'Theology - Moral / Ethics',
    'Theology - Sacramental',
    'Theology - Scriptural / Exegesis',
    'Theology - Trinitarian',
    'Towns / Cities',
    'Travel / Pilgrimage',
    'Vikings',
    'War - Chivalry',
    'War - Military History',
    'Women / Gender' ]
  end


end
